version: "3.8"

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always

  wp-php:
    build:
      context: requirements/wp-php
      dockerfile: Dockerfile
    container_name: wp-php
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
    expose:
      - "9000"

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wp-php
    env_file:
      - .env
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
    ports:
      - "443:443"

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agtshiba/data/mariadb

  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agtshiba/data/web

networks:
  inception:
    driver: bridge

