services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
    expose:
      - "9000"

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
    ports:
      - "443:443"

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agtshiba/data/mariadb

  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agtshiba/data/web

networks:
  inception:
    driver: bridge

